[package]
name = "pliron-inspect-driver"
description = "Driver library for pliron-inspect: render documents + stdio protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords = ["pliron", "compiler", "ir", "driver"]
categories = ["compilers", "development-tools"]

[dependencies]
pliron.workspace = true
pliron-llvm.workspace = true
pliron-inspect-protocol.workspace = true
pliron-inspect-lsp.workspace = true
lsp-types = "0.95"
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
flowblocks = "0.2"
clap.workspace = true
