[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/montaglue/pliron-inspect"
readme = "README.md"

[workspace.dependencies]
pliron = "0.17.0"
pliron-llvm = { version = "0.17.0", default-features = false }
pliron-inspect-protocol = { version = "0.1.0", path = "crates/protocol" }
pliron-inspect-driver = { version = "0.1.0", path = "crates/driver" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
