[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
pliron = { path = "../pliron-master" }
pliron-inspect-protocol = { path = "crates/protocol" }
pliron-inspect-driver = { path = "crates/driver" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
